# Generated by Django 5.1.2 on 2025-08-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_alter_campoparteproducto_opciones_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='svg_textura_1',
            field=models.FileField(help_text='Archivo *.jpg, *.png, etc., correspondiente a texturas de svg', null=True, upload_to='producto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='svg_textura_2',
            field=models.FileField(help_text='Archivo *.jpg, *.png, etc., correspondiente a texturas de svg', null=True, upload_to='producto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='svg_textura_3',
            field=models.FileField(help_text='Archivo *.jpg, *.png, etc., correspondiente a texturas de svg', null=True, upload_to='producto/'),
        ),
    ]
